### ISSUE TITLE
gulp server性能提升

### ISSUE THREAD

**Issue by paseo** [uxcore/generator-uxcore#7]
gulp server指令现在的实现方式是每次重新webpack打包，耗时太长。开发不便利。

**Comment by eternalsky** [comment]
webpack 打包是必须的，这是由于 react 使用 commonjs 规范造成的，速度慢一方面是因为依赖的库太多，另一方面是因为browser-sync 本身也慢，后续会替换掉，同时引入类似项目的 fs-memory 来提高 io 性能
